---
- name: install docker
  yum:
    name: docker
    state: present

- name: install python docker packages
#  become: true
#  become_method: sudo
  pip:
    name: docker-py
    state: present

- name: ensure docker is started and enabled at boot
#  become: true
#  become_method: sudo
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: ensure handlers are notified now to avoid firewall conflicts
  meta: flush_handlers

- name: ensure docker users are added to the docker group
#  become: true
#  become_method: sudo
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
