---
- name: install docker
  yum:
    name: docker
    state: present

#- name: install python docker packages
#  pip:
#    name: docker-py
#    state: present

- name: ensure handlers are notified now to avoid firewall conflicts
  meta: flush_handlers
